### ISSUE TITLE
[bug] Useless features not written to database

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#89] opened 2019-02-07 10:28 UTC
Tested with binary selection.

**Comment by bendixsonnenberg** [comment] 2019-02-09 14:48
does this still happen?
are there special steps needed to provoke this behaviour?
currently I can't reproduce this

**Comment by bendixsonnenberg** [comment] 2019-02-09 21:58
in case this was in respect to skip round, this is fixed as of 
93568195a1380f7eb47baa542f975d8860ea776c

**Closed** 2019-02-11 08:25 UTC
Labels: bug
