### ISSUE TITLE
Game Creation: dataset for second game not stored in DB

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#94] opened 2019-02-07 11:12 UTC
when creating two games that use the same dataset, the database entry for the second game contains `NULL` for the dataset.

When trying to play the second game, an exception is thrown:
```
mlserver_1_c05202c48acd | <simpleError in (function (dataset) {    if (missing(dataset)) {        stop("Param \"dataset\" is required.")    }    fileName <- paste0("datasets/", dataset, ".zip")    if (file.exists(fileName)) {        return(readBin(fileName, "raw", n = file.info(fileName)$size))    }    else {        stop(paste0("Dataset \"", dataset, "\" not found on server."))    }})(dataset = "null"): Dataset "null" not found on server.>
tomcat_1_788b6231f12d | java.io.IOException: Server returned HTTP response code: 500 for URL: http://mlserver:8000/features?dataset=null
tomcat_1_788b6231f12d | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
tomcat_1_788b6231f12d | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
tomcat_1_788b6231f12d | 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1484)
tomcat_1_788b6231f12d | 	at com.csselect.mlserver.RESTMLServer.writeDataset(RESTMLServer.java:95)
tomcat_1_788b6231f12d | 	at com.csselect.mlserver.RESTMLServer.getFeatures(RESTMLServer.java:54)
tomcat_1_788b6231f12d | 	at com.csselect.database.mysql.MysqlGameAdapter.getFeatures(MysqlGameAdapter.java:82)
tomcat_1_788b6231f12d | 	at com.csselect.game.Game.getFeatureSet(Game.java:141)
tomcat_1_788b6231f12d | 	at com.csselect.game.Round.setGame(Round.java:57)
tomcat_1_788b6231f12d | 	at com.csselect.game.Game.startRound(Game.java:292)
tomcat_1_788b6231f12d | 	at com.csselect.user.Player.startRound(Player.java:79)
tomcat_1_788b6231f12d | 	at com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:130)
tomcat_1_788b6231f12d | 	at com.csselect.API.httpAPI.Games.startRound(Games.java:125)
tomcat_1_788b6231f12d | 	at com.csselect.API.httpAPI.Games.post(Games.java:66)
tomcat_1_788b6231f12d | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:102)
tomcat_1_788b6231f12d | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1_788b6231f12d | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1_788b6231f12d | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tomcat_1_788b6231f12d | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tomcat_1_788b6231f12d | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
tomcat_1_788b6231f12d | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
tomcat_1_788b6231f12d | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
tomcat_1_788b6231f12d | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tomcat_1_788b6231f12d | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
tomcat_1_788b6231f12d | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
tomcat_1_788b6231f12d | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
tomcat_1_788b6231f12d | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
tomcat_1_788b6231f12d | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tomcat_1_788b6231f12d | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tomcat_1_788b6231f12d | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tomcat_1_788b6231f12d | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tomcat_1_788b6231f12d | 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by NicoWeidmann** [comment] 2019-02-07 12:28
It seems like the dataset is only properly stored for the first game after startup of the server.

**Comment by bendixsonnenberg** [comment] 2019-02-09 15:37
currently can't reproduce

**Comment by NicoWeidmann** [comment] 2019-02-09 22:21
1. create 1 organizer and 1 player account
2. log in as organizer
3. create game in binary select mode, invite the 1 player, 10 rounds, data set populationGender
4. return to organizer dashboard
5. create another game in binary select mode, invite the 1 player, 13 rounds, data set populationGender
6. in DB, the second game doesn't have the data set stored:

<img width="897" alt="bildschirmfoto 2019-02-09 um 23 21 02" src="https://user-images.githubusercontent.com/24777609/52526970-679a8180-2cc1-11e9-8c15-128c92920c11.png">

**Comment by bendixsonnenberg** [comment] 2019-02-09 22:40
Do you use the correct MySQL Version,this was an issue with the new versionsOn Feb 9, 2019 23:21, Nico Weidmann <notifications@github.com> wrote:create 1 organizer and 1 player accountlog in as organizercreate game in binary select mode, invite the 1 player, 10 rounds, data set populationGenderreturn to organizer dashboardcreate another game in binary select mode, invite the 1 player, 13 rounds, data set populationGenderin DB, the second game doesn't have the data set stored:

**Comment by NicoWeidmann** [comment] 2019-02-09 22:53
I don't know, I use the current version of the docker container. I'll check later.

**Comment by NicoWeidmann** [comment] 2019-02-10 20:37
I'm using MySQL 5.7.20. That's the right one, isn't it? At least it says so in the Readme.

**Comment by SeineEloquenz** [comment] 2019-02-11 10:15
That's the one we know that everything should work on, yes.
I'm going to take a look into it once I have my workspace setup again

**Comment by bendixsonnenberg** [comment] 2019-02-11 17:20
```
tomcat_1    | 2019-02-11 16:50:02 [http-nio-8080-exec-93] com.csselect.database.mysql.MysqlGameAdapter.getFeatures()
tomcat_1    | ERROR: javax.imageio.IIOException: Caught exception during read: 
tomcat_1    | 	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1686)
tomcat_1    | 	at com.csselect.utils.ImageUtils.readImage(ImageUtils.java:31)
tomcat_1    | 	at com.csselect.utils.FeatureSetUtils.loadFeatureSet(FeatureSetUtils.java:60)
tomcat_1    | 	at com.csselect.mlserver.RESTMLServer.getFeatures(RESTMLServer.java:61)
tomcat_1    | 	at com.csselect.database.mysql.MysqlGameAdapter.getFeatures(MysqlGameAdapter.java:88)
tomcat_1    | 	at com.csselect.game.Game.getFeatureSet(Game.java:141)
tomcat_1    | 	at com.csselect.game.Round.setGame(Round.java:68)
tomcat_1    | 	at com.csselect.game.Game.startRound(Game.java:292)
tomcat_1    | 	at com.csselect.user.Player.startRound(Player.java:85)
tomcat_1    | 	at com.csselect.API.APIFacadePlayer.startRound(APIFacadePlayer.java:138)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.startRound(Games.java:129)
tomcat_1    | 	at com.csselect.API.httpAPI.Games.post(Games.java:67)
tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:102)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tomcat_1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tomcat_1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
tomcat_1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tomcat_1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
tomcat_1    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
tomcat_1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
tomcat_1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tomcat_1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
tomcat_1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
tomcat_1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
tomcat_1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
tomcat_1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tomcat_1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tomcat_1    | 	at java.base/java.lang.Thread.run(Thread.java:844)
tomcat_1    | Caused by: java.lang.OutOfMemoryError: Java heap space
tomcat_1    | 2019-02-11 16:51:09 [http-nio-8080-exec-94] com.csselect.game.gamecreation.GameCreator.doCreate()
tomcat_1    | ERROR: javax.imageio.IIOException: Caught exception during read: 
tomcat_1    | 	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1686)
tomcat_1    | 	at com.csselect.utils.ImageUtils.readImage(ImageUtils.java:31)
tomcat_1    | 	at com.csselect.utils.FeatureSetUtils.loadFeatureSet(FeatureSetUtils.java:60)
tomcat_1    | 	at com.csselect.mlserver.RESTMLServer.getFeatures(RESTMLServer.java:61)
tomcat_1    | 	at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:112)
tomcat_1    | 	at com.csselect.user.Organiser.createGame(Organiser.java:72)
tomcat_1    | 	at com.csselect.API.APIFacadeOrganiser.createGame(APIFacadeOrganiser.java:142)
tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.createGame(GameManagement.java:169)
tomcat_1    | 	at com.csselect.API.httpAPI.GameManagement.post(GameManagement.java:78)
tomcat_1    | 	at com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:102)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
tomcat_1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tomcat_1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tomcat_1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tomcat_1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tomcat_1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
tomcat_1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tomcat_1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
tomcat_1    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
tomcat_1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
tomcat_1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tomcat_1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
tomcat_1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
tomcat_1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
tomcat_1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
tomcat_1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tomcat_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tomcat_1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tomcat_1    | 	at java.base/java.lang.Thread.run(Thread.java:844)
tomcat_1    | Caused by: java.lang.OutOfMemoryError: Java heap space
```
had the same thing happen to me. Restarting the docker container solved it for me.
Take a look at the last line of the log 'Out of memory' I'm not sure what could cause this, but it seems that in some way we are aggregating memory and not releasing it

**Comment by SeineEloquenz** [comment] 2019-02-11 18:02
Do you know how much memory our application has in the docker container? But I don't see why we should run into memory issues as the only "heavy" operation is loading and holding the featuresets in memory

**Comment by bendixsonnenberg** [comment] 2019-02-11 18:12
of my 10 GB ram the docker container used about 3,

**Comment by SeineEloquenz** [comment] 2019-02-11 18:34
So we can safely assume that the about 30mb of the featureSet most likely won't be the issue

**Comment by Santaaa348** [comment] 2019-02-11 20:17
This happens to me too. I can play many rounds of the same game, but when I want to play a round of another game I get the same `OutOfMemory` error as mentined above.

**Comment by SeineEloquenz** [comment] 2019-02-11 20:19
I'll make the MLServer store the featureSets in a hashmap so that every featureset can only exist at most once, hopefully the featuresets were the problem and this will fix it

**Comment by SeineEloquenz** [comment] 2019-02-11 22:05
RESTMLServer now ensures that featureSets only ever get loaded once into memory as of c2ad435, maybe this helps

**Comment by SeineEloquenz** [comment] 2019-02-11 22:30
How large is the default heap size for the JVM in the docker container @bendixsonnenberg? Maybe it is very low by default? I can't think of a better reason as we don't really aggregate significant amounts of memory anywhere

**Comment by Santaaa348** [comment] 2019-02-12 08:30
Does work for me now.

**Comment by Santaaa348** [comment] 2019-02-12 08:53
But it happened again under different circumstances.. 🤔

**Comment by bendixsonnenberg** [comment] 2019-02-12 13:51
I've looked into it, and it seems that memory leaking is a problem that is known for tomcat([example](https://stackoverflow.com/questions/41718907/memory-leak-when-redeploying-application-in-tomcat)).
the problem starts to exist after redeploying multiple times, since tomcat does not allow the GC to collect the old threads for connections. The solution is to restart the tomcat server every now and then during development. During production this is not a problem, since contentious redeploying will not happen there

**Comment by SeineEloquenz** [comment] 2019-02-13 15:01
So can we close this issue as it seems to be a tomcat issue and not on our end?

**Comment by bendixsonnenberg** [comment] 2019-02-13 15:21
we should add a section to the readme explaining that in case this issue occurs the solution is to restart tomcat and/or advise that if this issue is a problem for their use-case the should look into other war hosting servers that do not suffer from this issue. As far as i know our application does not use tomcat specific code, so it should be possible to use another implementation
[list of other servers on wikipedia](https://en.wikipedia.org/wiki/Web_container)

**Closed** 2019-02-13 23:43 UTC
Labels: bug
