### ISSUE TITLE
Daily Challenge: no challenge shown

### ISSUE THREAD

**Issue by NicoWeidmann** [bendixsonnenberg/CS-Select#101] opened 2019-02-07 12:42 UTC
Under some conditions no daily challenge is shown in the player dashboard:
![bildschirmfoto 2019-02-07 um 13 40 18](https://user-images.githubusercontent.com/24777609/52412154-39a91780-2ade-11e9-9eec-3aa3c1d4aaa0.png)

After logging out and back in, a challenge is shown.

**Comment by Santaaa348** [comment] 2019-02-09 18:01
I can't reproduce this. I tried this under lots of circumstances and every of the existing challenges have been shown. Do you have more information?

**Comment by NicoWeidmann** [comment] 2019-02-09 22:14
This happened when registering a new user account and being redirected to the player dashboard for the first time. However, I just pulled the newest version and the bug seems to be fixed already.

**Comment by Santaaa348** [comment] 2019-02-09 23:12
Alright, then I'm closing this as it seems to be fixed.

**Closed by Santaaa348** 2019-02-09 23:12 UTC
Labels: bug
